---
###################################################################
# Playbook and scripts provided by Red Hat Consulting come as is
# and without any warranties.
###################################################################
#
- name: Backing up the OpenStack Databases of the overcloud
  hosts: overcloud_controllers
  become: true
  vars:
    hiera_config_file: '/etc/hiera.yaml'
    nfs_src_mount: '172.16.255.100:/lv_data/backups/openstack_backups'
    nfs_client_mount_directory: '/backups'
    nfs_client_mount_options: 'rw,sync'
    backup_directory_base: '/backups/database_backups'
    backup_directory_today: 'overcloud-databases-backup-{{ ansible_date_time.iso8601_basic_short }}'
    database_dump_file_grants_db: 'overcloud-database-backup-grants-{{ ansible_date_time.iso8601_basic_short }}.gz'
    database_dump_file_openstack_db: 'overcloud-database-backup-openstack-{{ ansible_date_time.iso8601_basic_short }}.gz'
  tasks:
   -  import_tasks: ./tasks/overcloud_database_backup.yml

